version: "3.9"

services:
  backend:
    build: ./backend
    container_name: astrocopilot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: astrocopilot-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
